import {sanitizeSegments,toTXT,toSRT,toLRC,activeIndex} from './utils.js';
const $=s=>document.querySelector(s); let archivo=null, lineas=[], audioUrl=null;
const entrada=$('#archivo-audio'), zona=$('#zona-subida'), transcribir=$('#boton-transcribir');
$('#boton-seleccionar').onclick=e=>{e.stopPropagation();entrada.click()}; zona.onclick=()=>entrada.click(); zona.onkeydown=e=>{if(e.key==='Enter'||e.key===' ')entrada.click()};
['dragenter','dragover'].forEach(ev=>zona.addEventListener(ev,e=>{e.preventDefault();zona.classList.add('arrastrando')})); ['dragleave','drop'].forEach(ev=>zona.addEventListener(ev,e=>{e.preventDefault();zona.classList.remove('arrastrando')})); zona.ondrop=e=>cargarArchivo(e.dataTransfer.files[0]); entrada.onchange=()=>cargarArchivo(entrada.files[0]);
function cargarArchivo(file){if(!file)return;if(!/\.mp3$/i.test(file.name)&&file.type!=='audio/mpeg'){alert('Selecciona un archivo MP3 válido.');return}archivo=file;$('#nombre-archivo').textContent=file.name;$('#datos-archivo').textContent=`${(file.size/1048576).toFixed(1)} MB · listo para procesar`;$('#archivo-seleccionado').classList.remove('oculto');transcribir.disabled=false;if(audioUrl)URL.revokeObjectURL(audioUrl);audioUrl=URL.createObjectURL(file);$('#reproductor').src=audioUrl}
$('#quitar-archivo').onclick=()=>{archivo=null;entrada.value='';transcribir.disabled=true;$('#archivo-seleccionado').classList.add('oculto')};
function estado(titulo,detalle){$('#estado').classList.remove('oculto');$('#estado-titulo').textContent=titulo;$('#estado-detalle').textContent=detalle}
transcribir.onclick=async()=>{if(!archivo)return;transcribir.disabled=true;try{estado('Preparando el audio…','Convirtiendo la canción a audio mono de 16 kHz.');const audio=await decodificar(archivo);estado('Cargando la inteligencia artificial…','La primera descarga puede pesar alrededor de 75 MB; después quedará en la memoria del navegador.');const {pipeline,env}=await import('https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.7.3');env.allowLocalModels=false;const pipe=await pipeline('automatic-speech-recognition','onnx-community/whisper-tiny',{dtype:'q8',device:'wasm',progress_callback:p=>{if(p.status==='progress')$('#estado-detalle').textContent=`Descargando modelo: ${Math.round(p.progress||0)} %`}});estado('Escuchando la canción…','Whisper está identificando las palabras y sus tiempos.');const out=await pipe(audio,{language:'spanish',task:'transcribe',return_timestamps:true,chunk_length_s:30,stride_length_s:5});lineas=sanitizeSegments(out.chunks||[{text:out.text,start:0,end:audio.length/16000}]);if(!lineas.length)throw new Error('No se detectó voz. Intenta con una canción donde la voz se escuche más clara.');mostrarEditor()}catch(e){console.error(e);alert(`No se pudo completar la transcripción: ${e.message||e}`)}finally{$('#estado').classList.add('oculto');transcribir.disabled=false}};
async function decodificar(file){const ctx=new AudioContext({sampleRate:16000});const buf=await ctx.decodeAudioData(await file.arrayBuffer());const offline=new OfflineAudioContext(1,Math.ceil(buf.duration*16000),16000),src=offline.createBufferSource();src.buffer=buf;src.connect(offline.destination);src.start();const rendered=await offline.startRendering();await ctx.close();return rendered.getChannelData(0)}
$('#boton-demo').onclick=()=>{lineas=[{start:0,end:4,text:'Esta es la historia que comienza hoy'},{start:4,end:8,text:'Una melodía, una nueva voz'},{start:8,end:12,text:'Cada palabra ilumina el camino'},{start:12,end:16,text:'Canta conmigo esta canción'}];mostrarEditor()};
function mostrarEditor(){renderLineas();$('#editor').classList.remove('oculto');$('#editor').scrollIntoView({behavior:'smooth'});document.querySelectorAll('.pasos li')[2].classList.add('activo')}
function renderLineas(){const box=$('#lineas');box.innerHTML='';lineas.forEach((l,i)=>{const row=document.createElement('div');row.className='linea';row.innerHTML=`<input type="number" min="0" step="0.1" value="${l.start.toFixed(1)}" aria-label="Inicio del verso ${i+1}"><input type="number" min="0" step="0.1" value="${l.end.toFixed(1)}" aria-label="Fin del verso ${i+1}"><input value="${escapeHtml(l.text)}" aria-label="Texto del verso ${i+1}"><button aria-label="Eliminar verso ${i+1}">×</button>`;const inputs=row.querySelectorAll('input');inputs[0].onchange=()=>l.start=+inputs[0].value;inputs[1].onchange=()=>l.end=+inputs[1].value;inputs[2].oninput=()=>l.text=inputs[2].value;row.querySelector('button').onclick=()=>{lineas.splice(i,1);renderLineas()};box.append(row)})}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
$('#agregar-linea').onclick=()=>{const end=lineas.at(-1)?.end||0;lineas.push({start:end,end:end+3,text:'Nuevo verso'});renderLineas()};
function descargar(text,nombre,tipo='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:tipo}));a.download=nombre;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('#descargar-txt').onclick=()=>descargar(toTXT(lineas),'letra.txt');$('#descargar-srt').onclick=()=>descargar(toSRT(lineas),'letra.srt');$('#descargar-lrc').onclick=()=>descargar(toLRC(lineas),'letra.lrc');
$('#ir-karaoke').onclick=()=>{$('#karaoke').classList.remove('oculto');$('#karaoke').scrollIntoView({behavior:'smooth'});document.querySelectorAll('.pasos li')[3].classList.add('activo');actualizarKaraoke(0)};
const player=$('#reproductor');player.ontimeupdate=()=>actualizarKaraoke(player.currentTime);function actualizarKaraoke(t){const i=activeIndex(lineas,t);$('#letra-anterior').textContent=lineas[i-1]?.text||'';$('#letra-actual').textContent=lineas[i]?.text||'Tu letra aparecerá aquí';$('#letra-siguiente').textContent=lineas[i+1]?.text||''}
$('#estilo').onchange=e=>{$('#pantalla-karaoke').className=`pantalla ${e.target.value}`};$('#formato').onchange=e=>{const p=$('#pantalla-karaoke');p.classList.remove('vertical','cuadrado');if(e.target.value!=='horizontal')p.classList.add(e.target.value)};
$('#grabar-video').onclick=async()=>{if(!archivo){alert('Para grabar el video, primero selecciona el MP3 original.');return}const btn=$('#grabar-video');btn.disabled=true;btn.textContent='Grabando…';try{await grabarKaraoke()}catch(e){console.error(e);alert(`No fue posible grabar: ${e.message}`)}finally{btn.disabled=false;btn.textContent='Grabar video karaoke'}};
async function grabarKaraoke(){const formato=$('#formato').value,dims=formato==='vertical'?[720,1280]:formato==='cuadrado'?[900,900]:[1280,720],canvas=document.createElement('canvas');[canvas.width,canvas.height]=dims;const ctx=canvas.getContext('2d'),ac=new AudioContext(),source=ac.createMediaElementSource(player),dest=ac.createMediaStreamDestination();source.connect(dest);source.connect(ac.destination);const stream=canvas.captureStream(30);dest.stream.getAudioTracks().forEach(t=>stream.addTrack(t));const mp4=MediaRecorder.isTypeSupported('video/mp4;codecs=avc1,mp4a.40.2'),mime=mp4?'video/mp4;codecs=avc1,mp4a.40.2':'video/webm;codecs=vp9,opus',rec=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:5000000}),parts=[];rec.ondataavailable=e=>e.data.size&&parts.push(e.data);const terminado=new Promise(r=>rec.onstop=r);function dibujar(){const w=canvas.width,h=canvas.height,style=$('#estilo').value,g=ctx.createRadialGradient(w/2,h*.4,10,w/2,h*.5,w*.7);if(style==='oceano'){g.addColorStop(0,'#05678a');g.addColorStop(1,'#041a34')}else if(style==='clasico'){g.addColorStop(0,'#3c3c3c');g.addColorStop(1,'#080808')}else{g.addColorStop(0,'#49247c');g.addColorStop(1,'#100921')}ctx.fillStyle=g;ctx.fillRect(0,0,w,h);const i=activeIndex(lineas,player.currentTime);ctx.textAlign='center';ctx.fillStyle='#ffffff77';ctx.font=`600 ${Math.round(h*.025)}px sans-serif`;ctx.fillText('MULTIFAZÉTICO LYRICS SOLUTIONS',w/2,h*.1);drawText(ctx,lineas[i-1]?.text||'',w/2,h*.35,w*.82,Math.round(h*.045),'#ffffff55');drawText(ctx,lineas[i]?.text||'',w/2,h*.52,w*.85,Math.round(h*.065),style==='clasico'?'#ffe36a':'#fff');drawText(ctx,lineas[i+1]?.text||'',w/2,h*.7,w*.82,Math.round(h*.045),'#ffffff55');if(!player.paused)requestAnimationFrame(dibujar)}player.currentTime=0;await ac.resume();rec.start(1000);player.onended=()=>rec.stop();await player.play();dibujar();await terminado;await ac.close();descargar(new Blob(parts,{type:mime}),`karaoke.${mp4?'mp4':'webm'}`,mime)}
function drawText(ctx,text,x,y,maxWidth,size,color){ctx.fillStyle=color;ctx.font=`900 ${size}px sans-serif`;const words=text.split(' '),rows=[];let row='';for(const word of words){const test=(row+' '+word).trim();if(ctx.measureText(test).width>maxWidth&&row){rows.push(row);row=word}else row=test}if(row)rows.push(row);rows.forEach((r,i)=>ctx.fillText(r,x,y+(i-(rows.length-1)/2)*size*1.2))}
